export const GET_WORKOUT_SCHEDULE_PENDING = 'GET_WORKOUT_SCHEDULE_PENDING';
export const GET_WORKOUT_SCHEDULE_SUCCESS = 'GET_WORKOUT_SCHEDULE_SUCCESS';
export const GET_WORKOUT_SCHEDULE_FAILED = 'GET_WORKOUT_SCHEDULE_FAILED';
