export const GET_WORKOUT_SCHEDULE_PENDING = 'GET_WORKOUT_SCHEDULE_PENDING';
export const GET_WORKOUT_SCHEDULE_SUCCESS = 'GET_WORKOUT_SCHEDULE_SUCCESS';
export const GET_WORKOUT_SCHEDULE_FAILED = 'GET_WORKOUT_SCHEDULE_FAILED';

export const GET_EXERCISES_PENDING = 'GET_EXERCISES_PENDING';
export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export const GET_EXERCISES_FAILED = 'GET_EXERCISES_FAILED';

export const GET_TECHNIQUES_PENDING = 'GET_TECHNIQUES_PENDING';
export const GET_TECHNIQUES_SUCCESS = 'GET_TECHNIQUES_SUCCESS';
export const GET_TECHNIQUES_FAILED = 'GET_TECHNIQUES_FAILED';
